### ISSUE TITLE
Unable to connect to my Xamarin android app

### ISSUE THREAD

**Issue by hmahajanHM** [michaeled/uisleuth#1]
![untitled](https://user-images.githubusercontent.com/13818991/30019950-d7fe7294-917f-11e7-837e-4500a9636c23.png)
Hi i am using Azure VM with Visual studio community 2017. I simply created New Project--> Cross-Platform--> Cross Platform App( Forms). then followed following steps: https://xamarinhelp.com/uisleuth-visually-inspect-xamarin-forms-application/. But still get below error.
![Uploading image.png…]()

**Comment by michaeled** [comment]
see #2

**Comment by hmahajanHM** [comment]
Thanks michaeled. I opened UiSleuth application today to follow the steps you mentioned. Now another  issue before I can fix the 1st one.
![uisleuth issue](https://user-images.githubusercontent.com/13818991/30588631-18f73a0c-9d55-11e7-972a-fdbba9ef54da.JPG)
The connection list is too long from last retry 10 days back. Now I get this screen today and no option to remove this list or shorten this list.
To me UiSleuth is still half baked to be used by developers. Highly disappointing.

**Comment by michaeled** [comment]
Hey @hmahajanHM,

I'm sorry you're disappointed. Please remember that UI Sleuth is free and open-source software.
However, thank you for reporting the bug. This alone makes the product better. I won't be contributing to UI Sleuth for another 2 months because of my current work schedule. So, feel free to send me a pull request with a bug fix.

**Comment by michaeled** [comment]
fix committed to main.
